version: '3.9'
services:
  raspberrypi_app:
    image: raspberrypi-wifi-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raspberrypi-app-container
    privileged: true
    network_mode: "host"
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
    volumes:
      - "/etc/hostapd/hostapd.conf:/etc/hostapd/hostapd.conf"
      - "/etc/dnsmasq.conf:/etc/dnsmasq.conf"
    ports:
      - "5000:5000"
      - "12345:12345"
      - "12346:12346"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["python", "app.py"]
