version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    devices:
      - /dev/i2c-1:/dev/i2c-1
      - /dev/gpiomem:/dev/gpiomem
    ports:
      - "12345:12345"
      - "12346:12346"
      - "50000:50000"
      - "8554:8554"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "server.py"]
